AllCops:
  TargetRubyVersion: 2.5

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 79

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Style/RegexpLiteral:
  EnforcedStyle: slashes

Lint/BooleanSymbol:
  Enabled: false
